# Generated by Django 4.2.5 on 2023-10-01 19:47

from django.db import migrations, models
import robots.validators


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_alter_robot_id_alter_robot_model_alter_robot_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='serial',
            field=models.CharField(max_length=5, validators=[robots.validators.validate_serial]),
        ),
    ]
