openapi: 3.0.2
info:
  title: 'RC4 API'
  version: '0.1'
paths:
  /api/robots/:
    post:
      summary: Создает нового робота
      operationId: createRobot
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Robot'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Robot'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Robot'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Robot'
          description: 'Успех'
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Robot'
          description: 'Неверный запрос'
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Robot'
          description: 'Ошибка при выполнении операции'
      tags:
      - robot

components:
  schemas:
    Robot:
      type: object
      title: Robot
      description: Робот
      properties:
        id:
          type: integer
          format: int64
          description: Уникальное целое число, определяющее этого робота
          readOnly: true
        model:
          type: string
          description: Модель
          maxLength: 2
        version:
          type: string
          description: Версия
          maxLength: 2
        created:
          type: string
          format: datetime
          description: Дата и время создания
      required:
      - serial
      - model
      - version
      - created
